version: '3.0'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: techtalk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
